apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: drifthawk
resources:
  - ../../rollouts/ops-bot.yaml
  - ../../namespaces/staging/namespace.yaml
  - ../../network/ops-bot-netpol.yaml
images:
  - name: ghcr.io/OWNER/drifthawk-ops-bot
    newTag: sha256:PINNED_DIGEST
configMapGenerator:
  - name: ops-bot-config
    literals:
      - LOG_LEVEL=INFO


