apiVersion: v1
kind: LimitRange
metadata:
  name: lr-staging
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: "200m"
        memory: 256Mi

