version: "3.9"
services:
  ops-bot:
    build:
      context: .
      dockerfile: Dockerfile.ops-bot
    ports:
      - "8080:8080"
    env_file:
      - ops_bot/.env.example
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

