apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: drifthawk
  app.kubernetes.io/managed-by: gitops
commonAnnotations:
  app.kubernetes.io/version: prod
resources:
  - ../../rollouts/ops-bot.yaml
  - ../../namespaces/prod/namespace.yaml
  - ../../network/ops-bot-netpol.yaml
  - ../../rollouts/ops-bot-hpa.yaml
  - ../../rollouts/ops-bot-sa.yaml
  - ../../rollouts/ops-bot-pdb.yaml
  - ./resourcequota.yaml
  - ./limitrange.yaml
images:
  - name: ghcr.io/OWNER/drifthawk-ops-bot
    newTag: sha256:PINNED_DIGEST
configMapGenerator:
  - name: ops-bot-config
    literals:
      - LOG_LEVEL=WARNING
      - LOG_FORMAT=json
secretGenerator:
  - name: ops-bot-secrets
    literals:
      - PLACEHOLDER=1
patches:
  - target: { kind: Deployment, name: ops-bot }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3


