apiVersion: v1
kind: LimitRange
metadata:
  name: lr-prod
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 2Gi
      defaultRequest:
        cpu: "500m"
        memory: 512Mi

