apiVersion: v1
kind: LimitRange
metadata:
  name: lr-dev
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi

