name: drift-scout
on: { schedule: [{ cron: "17 3 * * *" }], workflow_dispatch: {} }
jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: bash ops-bot/jobs/drift_scout.sh
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }


