name: openapi
on: [workflow_dispatch]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo '{"openapi":"3.1.0"}' > artifacts/openapi.json
      - uses: actions/upload-artifact@v4
        with: { name: openapi, path: artifacts/openapi.json }

