name: secrets-check
on:
  workflow_dispatch:
  push:
    branches: [develop]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required GitHub Secrets are present
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          JIRA_BASE: ${{ secrets.JIRA_BASE }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          SNOW_INSTANCE: ${{ secrets.SNOW_INSTANCE }}
          SNOW_USER: ${{ secrets.SNOW_USER }}
          SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
        run: |
          set -euo pipefail
          missing=()
          for var in COSIGN_PRIVATE_KEY COSIGN_PASSWORD COSIGN_PUBLIC_KEY JIRA_BASE JIRA_USER JIRA_TOKEN; do
            if [ -z "${!var:-}" ]; then missing+=("$var"); fi
          done
          # Optional secrets
          for var in INFRACOST_API_KEY SNOW_INSTANCE SNOW_USER SNOW_TOKEN; do
            if [ -z "${!var:-}" ]; then echo "notice: optional secret $var not set"; fi
          done
          if [ ${#missing[@]} -gt 0 ]; then echo "Missing required secrets: ${missing[*]}"; exit 1; fi
          echo "All required secrets present."

