name: tests
on: [pull_request]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r ops_bot/requirements.txt -r ops_bot/requirements-dev.txt
      - run: pytest -q

