name: tfsec
on:
  pull_request:
  push:
    branches: [develop]
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: terraform/envs/dev

